encoder: Fix compile warnings due to unhandled enumeration values in a switch statement.
$HEVC/source/encoder/encoder.cpp: In member function â€˜void x265::Encoder::determineLevelAndProfile(x265_param_t*)â€™:
$HEVC/source/encoder/encoder.cpp:119:12: error: enumeration value â€˜NONEâ€™ not handled in switch [-Werror=switch]
     switch (m_level)
            ^
$HEVC/source/encoder/encoder.cpp:119:12: error: enumeration value â€˜LEVEL1â€™ not handled in switch [-Werror=switch]
$HEVC/source/encoder/encoder.cpp:119:12: error: enumeration value â€˜LEVEL2â€™ not handled in switch [-Werror=switch]
$HEVC/source/encoder/encoder.cpp:119:12: error: enumeration value â€˜LEVEL2_1â€™ not handled in switch [-Werror=switch]
$HEVC/source/encoder/encoder.cpp:119:12: error: enumeration value â€˜LEVEL3â€™ not handled in switch [-Werror=switch]
$HEVC/source/encoder/encoder.cpp:119:12: error: enumeration value â€˜LEVEL3_1â€™ not handled in switch [-Werror=switch]
cc1plus: all warnings being treated as errors